name:                pacalcbot
version:             0.1.0.0
github:              "fetsh-edu/pacalcbot"
license:             BSD3
author:              "fetsh"
maintainer:          "me@fetsh.me"
copyright:           "2023 fetsh"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/fetsh-edu/pacalcbot#readme>

dependencies:
- base >= 4.7 && < 5
- parsec
- text
- filepath
- directory
- yaml
- telegram-bot-api >= 6.7
- telegram-bot-simple >= 0.12
- warp
- warp-tls

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  pacalcbot-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - pacalcbot

tests:
  pacalcbot-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - pacalcbot
